CONFIG_DISPLAY=y                                                                                                     
CONFIG_GC9A01A=y  

# 基础配置
CONFIG_ZMK_KEYBOARD_NAME="Charybdis"

CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_ZMK_BATTERY=y


# USB 支持
CONFIG_ZMK_USB=y


# nRF USB 驱动
CONFIG_USB_NRFX=y
CONFIG_NRFX_USBD=y


